// Users
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
// Groups
export const LOAD_GROUP_SUCCESS = 'LOAD_GROUP_SUCCESS';
// Books
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
// Conversations
export const LOAD_CONVERSATIONS_SUCCESS = 'LOAD_CONVERSATIONS_SUCCESS';
export const LOAD_CONVERSATION_MESSAGES_SUCCESS = 'LOAD_CONVERSATION_MESSAGES_SUCCESS';
